default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  primary:
    <<: *default
    database: sample_app_production

  cache:
    <<: *default
    database: sample_app_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: sample_app_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: sample_app_production_cable
    migrations_paths: db/cable_migrate
